name: windows-2019

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  validate-dco:
    uses: ./.github/workflows/.dco.yml

  run:
    needs:
      - validate-dco
    uses: ./.github/workflows/.windows.yml
    strategy:
      fail-fast: false
      matrix:
        storage:
          - graphdriver
    with:
      os: windows-2019
      storage: ${{ matrix.storage }}
      send_coverage: false
